apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.be.configmap.name}}
data:
  DB_HOST: {{.Values.be.configmap.DB_HOST}}
  DB_NAME: {{.Values.be.configmap.DB_NAME}}
  DB_USER: {{.Values.be.configmap.DB_USER}}
  DB_PORT: {{.Values.be.configmap.DB_PORT}}
  PORT: {{.Values.be.configmap.PORT}}
  MODE: {{.Values.be.configmap.MODE}}
